spring:
  rabbitmq:
    host: amqp
    password: guest
    port: 5672
    username: guest
    listener:
      simple:
        default-requeue-rejected: false

amqp:
  inbox: accounting-service

db:
  host: postgres
  port: 5432
  name: accounting
  user: postgres
  password: admin


log4j:
  logger:
      org:
        springframework:
          jdbc:
            core:
              - JdbcTemplate: DEBUG, file
              - StatementCreatorUtils: TRACE, file
