spring:
  rabbitmq:
    host: amqp
    password: guest
    port: 5672
    username: guest

amqp:
  inbox: accounting-service

db:
  host: postgres
  port: 5432
  name: accounting
  user: postgres
  password: admin