spring:
  rabbitmq:
    host: amqp
    password: guest
    port: 5672
    username: guest
    listener:
      simple:
        default-requeue-rejected: false

amqp:
  inbox: analytics-service

db:
  host: postgres
  port: 5432
  name: analytics
  user: postgres
  password: admin