create sequence if not exists assigneeseq as integer start with 100 increment by 1;

create table if not exists assignee
(
    id integer generated by default as sequence assigneeseq primary key,
    assigneename varchar(64)
);

create sequence if not exists taskseq as integer start with 100 increment by 1;

create table if not exists task
(
    id integer generated by default as sequence taskseq primary key,
    description varchar(1024),
    assignee integer foreign key references assignee(id),
    status varchar(16)
);
