spring:
  rabbitmq:
    host: amqp
    password: guest
    port: 5672
    username: guest
    listener:
      simple:
        default-requeue-rejected: false

db:
  host: postgres
  port: 5432
  name: tasks
  user: postgres
  password: admin

amqp:
  inbox: tasks-service